# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [1]:
import pandas as pd

pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user", sep="|")[-5:]
# Ou encore
DS_first = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user", sep="|")
DS_first.head()

   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [2]:
DS_second = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv", sep=",")
DS_second.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [3]:
print(DS_second.columns.tolist())
print(DS_second.index.name)

['country', 'beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol', 'continent']
None

In [4]:
DS_second2 = DS_second.set_index("country")
DS_second2

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [6]:
DS_second.iloc[-1]

country                         Zimbabwe
beer_servings                         64
spirit_servings                       18
wine_servings                          4
total_litres_of_pure_alcohol         4.7
continent                         Africa
Name: 192, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [8]:
DS_second.iloc[-1,5:]

continent    Africa
Name: 192, dtype: object

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [11]:
DS_ufo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv", sep=",",header = 0, names=["city", "colors", "shape", "state", "time"])
DS_ufo
#ou

DS_ufo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv", sep=",")
DS_ufo = DS_ufo.rename(columns={
    "City": "city",
    "Colors Reported": "colors",
    "Shape Reported": "shape",
    "State": "state",
    "Time": "time"})
DS_ufo.head()

                   city colors     shape state             time
0                Ithaca    NaN  TRIANGLE    NY   6/1/1930 22:00
1           Willingboro    NaN     OTHER    NJ  6/30/1930 20:00
2               Holyoke    NaN      OVAL    CO  2/15/1931 14:00
3               Abilene    NaN      DISK    KS   6/1/1931 13:00
4  New York Worlds Fair    NaN     LIGHT    NY  4/18/1933 19:00

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [12]:
DS_ufo.iloc[:3,:]

          city colors     shape state             time
0       Ithaca    NaN  TRIANGLE    NY   6/1/1930 22:00
1  Willingboro    NaN     OTHER    NJ  6/30/1930 20:00
2      Holyoke    NaN      OVAL    CO  2/15/1931 14:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [15]:
DS_ufo.loc[:2]

          city colors     shape state             time
0       Ithaca    NaN  TRIANGLE    NY   6/1/1930 22:00
1  Willingboro    NaN     OTHER    NJ  6/30/1930 20:00
2      Holyoke    NaN      OVAL    CO  2/15/1931 14:00