# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [5]:
import pandas as pd

fruit_list = ['Apples', 'Bananas']
nb_list = [30,21]

df_fruit = pd.DataFrame([nb_list], columns= fruit_list)
df_fruit

   Apples  Bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [9]:
dict_fruit = {"2017 Sales": {"Apple": 35, "Bananas": 21},"2018 Sales": {"Apple": 41, "Bananas": 34}}

df_fruit2 = pd.DataFrame(dict_fruit)
df_fruit2 = df_fruit2.T
df_fruit2

            Apple  Bananas
2017 Sales     35       21
2018 Sales     41       34

In [12]:
fruitdict = {"2017 Sales":[35,21],"2018 Sales":[41,34]}
fruit_vendors = pd.DataFrame.from_dict(fruitdict, orient="index", columns=["Apples", "Bananas"])
print(fruit_vendors)

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [13]:
for x, y in fruit_vendors.items():
  print(x)
  print(y)

Apples
2017 Sales    35
2018 Sales    41
Name: Apples, dtype: int64
Bananas
2017 Sales    21
2018 Sales    34
Name: Bananas, dtype: int64

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [14]:
cut1 = fruit_vendors.iloc[1:]
print(cut1)

            Apples  Bananas
2018 Sales      41       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [18]:
cut2 = fruit_vendors.iloc[:,1:]
print(cut2)

            Bananas
2017 Sales       21
2018 Sales       34